version: '3.4'

networks:
  bankingnetwork:

services:
  banking.api:
    image: ${DOCKER_REGISTRY-}bankingapi
    ports:
    - '44340:8081'
    build:
      context: .
      dockerfile: Banking.API/Dockerfile
    depends_on:
      - pgdb
    networks:
      - bankingnetwork
      
  pgdb:
    image: postgres:14-alpine
    container_name: postgres
    networks:
        - bankingnetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 10

# Names our volume
volumes:
  pg-data: